[package]
name = "pilot-link-rs"
version = "0.1.0"
authors = ["andymememe <andymememe@gmail.com>"]
edition = "2018"

[lib]
name = "pilot_link"
path = "src/lib.rs"

[dependencies]
log = "0.4.8"
errno = "0.2.4"