[package]
name = "pilot-link-rs"
version = "0.1.0"
authors = ["andymememe <andymememe@gmail.com>"]
edition = "2018"

[lib]
name = "pilot_link"
path = "src/lib.rs"

[dependencies]
tzdata = "0.4.1"
num = "0.2.1"
num-derive = "0.3.0"
num-traits = "0.2.11"