[package]
name = "pilot-link-rs"
version = "0.1.0"
authors = ["andymememe <andymememe@gmail.com>"]
edition = "2021"

[lib]
name = "pilot_link"
path = "src/lib.rs"

[dependencies]
log = "0.4.17"
errno = "0.2.8"
serde = "1.0.137"
serde_derive = "1.0.137" 